CXXFLAGS=-std=c++11 -Wpedantic -Wall -Wextra -Werror -Weffc++ -Wzero-as-null-pointer-constant

test_matrix: test_matrix.cpp
	g++	$(CXXFLAGS)	test_matrix.cpp	-o	test_matrix

clean:
	/bin/rm test_matrix
